### ISSUE TITLE
sign_tool.py AA55AA55 vs 55AA55AA potential magic issue

### ISSUE THREAD

**Issue by nikitos1550** [xingrz/hi3861-bootstrap#1]
Hi! 

I am learning hi3861 and used your and https://github.com/koendv/hi3861_notes repos for quick start.
I found that on mine hi3861 dev pcba (same as on photo in `hi3861_notes` repo main readme page),
binary that packed with your script cannot be loaded, but if i change magic then it works ok.

```
diff --git a/tools/sign_tool.py b/tools/sign_tool.py
index ce58e0a..68598d7 100644
--- a/tools/sign_tool.py
+++ b/tools/sign_tool.py
@@ -27,7 +27,8 @@ def main():
 
         # Add 64-byte header
         header = bytearray()
-        header += struct.pack('>I', 0xAA55AA55)
+        #header += struct.pack('>I', 0xAA55AA55)
+        header += struct.pack('>I', 0x55AA55AA)
         header += struct.pack('<I', 56)
         header += bytearray([0] * 24)
         header += struct.pack('<I', 64)
@@ -43,7 +44,8 @@ def main():
         footer += hashlib.sha256(header + data).digest()
         footer += bytearray([0] * 8)
         footer += struct.pack('<I', len(data) + 64 + 48)
-        footer += struct.pack('>I', 0xAA55AA55)
+        #footer += struct.pack('>I', 0xAA55AA55)
+        footer += struct.pack('>I', 0x55AA55AA)
 
         f_out.write(header + data + footer)
```

Do you know anything about it? Does it depends on chip or something else?

P.S. `sign_tool` IMHO is not proper name for this tool, better name it `image_packer` or something like this, as `sign` make me think that there is some key or something like this, but actually there is nothing like this, it just some image wrapper that makes bin blob recognized by the bootrom.

**Comment by xingrz** [comment]
> Do you know anything about it? Does it depends on chip or something else?

Seems to be related to endianness but I'm not sure.

> P.S. `sign_tool` IMHO is not proper name for this tool, better name it `image_packer` or something like this

This follows the close-sourced `sign_tool.exe` in the official OpenHarmony project. In fact the image format has the ability to contain signatures, but I didn't implement that in my script. I'm not familiar with algorithms.

**Comment by nikitos1550** [comment]
Clear, thanks.
